title: Yuki Nishimura
description: Yuki Nishimura received his Doctor degree in Human Informatics from Ph.D. Program in Empowerment Informatics, University of Tsukuba, Japan in 2023. He is a Post-Doctoral Fellow at the Research Center for Intelligent Robotics,Zhejiang Lab, China.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
